name: DRG-LLaMA
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=66.0.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.20.3
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==5.0.1
      - anyio==3.7.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.39.0
      - black==23.3.0
      - bleach==6.0.0
      - blessed==1.20.0
      - cachetools==5.3.1
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - datasets==2.12.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.6
      - docker-pycreds==0.4.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastapi==0.95.2
      - fastjsonschema==2.17.1
      - ffmpy==0.3.0
      - filelock==3.12.0
      - fire==0.5.0
      - fonttools==4.39.4
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - genv==1.0.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - gpustat==1.1
      - gradio==3.32.0
      - gradio-client==0.2.5
      - grpcio==1.54.2
      - h11==0.14.0
      - httpcore==0.17.2
      - httpx==0.24.1
      - huggingface-hub==0.14.1
      - idna==3.4
      - ipykernel==6.23.1
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - kiwisolver==1.4.4
      - linkify-it-py==2.0.2
      - lit==16.0.5
      - loralib==0.1.1
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mistune==2.0.5
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - mypy-extensions==1.0.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==11.525.112
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - orjson==3.8.14
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.1
      - pathtools==0.1.2
      - peft==0.4.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==4.23.2
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.8
      - pydub==0.25.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.1.0
      - regex==2023.5.5
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.25.1
      - seqeval==1.2.2
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - starlette==0.27.0
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - thefuzz==0.19.0
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tokenize-rt==5.0.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.30.2
      - triton==2.0.0
      - typing-extensions==4.6.2
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - uri-template==1.2.0
      - urllib3==1.26.16
      - uvicorn==0.22.0
      - wandb==0.15.4
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - websockets==11.0.3
      - werkzeug==2.3.6
      - xxhash==3.2.0
      - yarl==1.9.2
prefix: /home/hanyinw2/miniconda3/envs/lora
